// nautilus_rlm.rs — Path A Integration with Nautilus TEE
// Extends oracle.rs to invoke RLM, verify evolution state, emit events
// Runs inside SGX enclave for verifiable private reasoning

use std::collections::HashMap;
use serde::{Deserialize, Serialize};
use blake3;

// Re-export from oracle.rs
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Breath {
    pub hash: Vec<u8>,
    pub prompt: String,
    pub timestamp_ms: u64,
    pub user_address: String,
    pub tone_vector: Vec<f32>,
    pub parent_hash: Vec<u8>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LobeResponse {
    pub lobe_id: u8,
    pub lobe_name: String,
    pub verdict: u8,  // 0=veto, 1=pass, 2=strong, 3=silence
    pub statement: String,
    pub domain: String,
    pub memory_chain_accessed: Vec<u8>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArgumentRound {
    pub breath_hash: Vec<u8>,
    pub epoch: u64,
    pub responses: Vec<LobeResponse>,
    pub rlm_depth: u64,
    pub timestamp_ms: u64,
    pub twelfth_face_triggered: bool,
    pub final_ashe: String,
}

// ============= VERIFIABLE EVOLUTION STATE =============

/// Tracks verified evolution state (on-chain equivalent)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EvolutionState {
    pub epoch: u64,
    pub last_memory_root: Vec<u8>,  // Walrus memory snapshot
    pub parent_memory_root: Vec<u8>, // Previous root (for DAG verification)
    pub breath_count: u64,
    pub last_evolution_ms: u64,
    pub treasury_balance: u64,      // SUI (in lamports, mock here)
    pub keeper_address: String,
}

/// Evolution proof (generated by oracle, verified on-chain)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EvolutionProof {
    pub epoch: u64,
    pub delta_hash: Vec<u8>,           // Hash of weight delta
    pub memory_root: Vec<u8>,          // New memory root
    pub parent_memory_root: Vec<u8>,   // Previous memory root
    pub ritual_rounds: Vec<ArgumentRound>,
    pub enclave_signature: Vec<u8>,    // Enclave signing key proof
    pub timestamp_ms: u64,
}

// ============= NAUTILUS RLM ORACLE =============

pub struct NautilusRLMOracle {
    pub evolution_state: EvolutionState,
    pub memory_dag: HashMap<Vec<u8>, Breath>,
    pub ritual_history: Vec<ArgumentRound>,
    pub encryption_key: Vec<u8>,
    pub enclave_key: Vec<u8>,  // Enclave private key for signing
}

impl NautilusRLMOracle {
    pub fn new(
        initial_epoch: u64,
        keeper_address: String,
        encryption_key: Vec<u8>,
        enclave_key: Vec<u8>,
    ) -> Self {
        NautilusRLMOracle {
            evolution_state: EvolutionState {
                epoch: initial_epoch,
                last_memory_root: vec![0u8; 32],
                parent_memory_root: vec![0u8; 32],
                breath_count: 0,
                last_evolution_ms: 0,
                treasury_balance: 1_000_000_000,  // 1 SUI (mock)
                keeper_address,
            },
            memory_dag: HashMap::new(),
            ritual_history: Vec::new(),
            encryption_key,
            enclave_key,
        }
    }

    /// MAIN ENTRY: Process EvolutionEvent from on-chain
    /// 1. Validate event signatures
    /// 2. Run ritual round (invoke RLM)
    /// 3. Generate evolution proof
    /// 4. Return proof for on-chain settlement
    pub fn process_evolution_event(
        &mut self,
        breaths: Vec<Breath>,
        claimed_epoch: u64,
        claimed_memory_root: Vec<u8>,
        claimed_delta_hash: Vec<u8>,
    ) -> Result<EvolutionProof, String> {
        // Validate: epoch must match
        if claimed_epoch != self.evolution_state.epoch + 1 {
            return Err(format!(
                "Epoch mismatch: claimed {}, expected {}",
                claimed_epoch,
                self.evolution_state.epoch + 1
            ));
        }

        // Validate: breath_count must match
        if breaths.len() as u64 != self.evolution_state.breath_count {
            return Err(format!(
                "Breath count mismatch: {} vs {}",
                breaths.len(),
                self.evolution_state.breath_count
            ));
        }

        // Store breaths in DAG
        let mut ritual_rounds = Vec::new();
        for breath in &breaths {
            self.memory_dag.insert(breath.hash.clone(), breath.clone());

            // Invoke RLM ritual round (stub: simplified)
            let round = self.ritual_round(breath, claimed_epoch);
            ritual_rounds.push(round);
        }

        // Verify memory root
        let computed_root = self.compute_memory_root();
        if computed_root != claimed_memory_root {
            return Err(format!(
                "Memory root mismatch: computed {:?}, claimed {:?}",
                hex::encode(&computed_root),
                hex::encode(&claimed_memory_root)
            ));
        }

        // Verify delta hash
        let computed_delta = self.compute_delta_hash(&ritual_rounds);
        if computed_delta != claimed_delta_hash {
            return Err(format!(
                "Delta hash mismatch: computed {:?}, claimed {:?}",
                hex::encode(&computed_delta),
                hex::encode(&claimed_delta_hash)
            ));
        }

        // Update state
        let parent_root = self.evolution_state.last_memory_root.clone();
        self.evolution_state.last_memory_root = claimed_memory_root.clone();
        self.evolution_state.parent_memory_root = parent_root.clone();
        self.evolution_state.epoch = claimed_epoch;
        self.evolution_state.breath_count = 0;
        self.evolution_state.last_evolution_ms = self.current_timestamp_ms();
        self.evolution_state.treasury_balance =
            self.evolution_state.treasury_balance.saturating_sub(1_000_000_000);

        // Store ritual rounds in history
        self.ritual_history.extend(ritual_rounds.clone());

        // Generate proof
        let proof = EvolutionProof {
            epoch: claimed_epoch,
            delta_hash: claimed_delta_hash,
            memory_root: claimed_memory_root,
            parent_memory_root,
            ritual_rounds,
            enclave_signature: self.sign_proof(&self.enclave_key),
            timestamp_ms: self.current_timestamp_ms(),
        };

        Ok(proof)
    }

    /// RITUAL ROUND: Invoke all 11 lobes (simplified stub)
    /// In real implementation: calls RLM (rlm_core.ts compiled to WASM in enclave)
    fn ritual_round(&self, breath: &Breath, epoch: u64) -> ArgumentRound {
        // Stub: generate synthetic responses
        let mut responses = Vec::new();

        for lobe_id in 1..=11 {
            let lobe_name = match lobe_id {
                1 => "Orunmila",
                2 => "Sango",
                3 => "Obatala",
                4 => "Ogun",
                5 => "Oshun",
                6 => "Oya",
                7 => "Yemoja",
                8 => "Eshu",
                9 => "Olokun",
                10 => "Osanyin",
                11 => "Egungun",
                _ => "Unknown",
            };

            let verdict = if lobe_id == 1 { 2 } else { 1 }; // Orunmila strong, others pass
            let statement = format!("[{} speaks]", lobe_name);
            let domain = "reasoning".to_string();
            let memory_hash = blake3::hash(
                format!("lobe_{}_{:?}", lobe_id, breath.hash).as_bytes(),
            )
            .as_bytes()
            .to_vec();

            responses.push(LobeResponse {
                lobe_id: lobe_id as u8,
                lobe_name: lobe_name.to_string(),
                verdict,
                statement,
                domain,
                memory_chain_accessed: memory_hash,
            });
        }

        ArgumentRound {
            breath_hash: breath.hash.clone(),
            epoch,
            responses,
            rlm_depth: 100, // Mock depth
            timestamp_ms: breath.timestamp_ms,
            twelfth_face_triggered: false,
            final_ashe: "ashe".to_string(),
        }
    }

    /// Compute memory root (hash of all DAG nodes)
    fn compute_memory_root(&self) -> Vec<u8> {
        let mut all_hashes = Vec::new();
        for (hash, _) in &self.memory_dag {
            all_hashes.extend_from_slice(hash);
        }
        blake3::hash(&all_hashes).as_bytes().to_vec()
    }

    /// Compute delta hash (hash of all ritual responses)
    fn compute_delta_hash(&self, rounds: &[ArgumentRound]) -> Vec<u8> {
        let mut delta_data = Vec::new();
        for round in rounds {
            for response in &round.responses {
                delta_data.extend_from_slice(&[response.verdict]);
                delta_data.extend_from_slice(response.statement.as_bytes());
            }
        }
        blake3::hash(&delta_data).as_bytes().to_vec()
    }

    /// Sign proof with enclave key (mock: just hash for now)
    fn sign_proof(&self, key: &[u8]) -> Vec<u8> {
        let mut combined = Vec::new();
        combined.extend_from_slice(key);
        combined.extend_from_slice(b"proof_signature");
        blake3::hash(&combined).as_bytes().to_vec()
    }

    /// Track breath (called on-chain via breath() entry function)
    pub fn track_breath(&mut self, breath_hash: Vec<u8>) {
        self.evolution_state.breath_count += 1;
    }

    /// Get current state (for on-chain verification)
    pub fn get_state(&self) -> EvolutionState {
        self.evolution_state.clone()
    }

    /// Verify evolution proof (called on-chain)
    pub fn verify_proof(&self, proof: &EvolutionProof) -> bool {
        // Check epoch
        if proof.epoch != self.evolution_state.epoch {
            return false;
        }

        // Check signature (stub: just verify non-empty)
        if proof.enclave_signature.is_empty() {
            return false;
        }

        // Check ritual rounds are non-empty
        if proof.ritual_rounds.is_empty() {
            return false;
        }

        true
    }

    /// Utility: current timestamp (milliseconds)
    fn current_timestamp_ms(&self) -> u64 {
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_millis() as u64
    }
}

// ============= TESTS =============

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_evolution_process() {
        let mut oracle = NautilusRLMOracle::new(0, "0xkeeper".to_string(), vec![0u8; 32], vec![0u8; 32]);

        let breath = Breath {
            hash: blake3::hash(b"test_breath").as_bytes().to_vec(),
            prompt: "What is the nature of being?".to_string(),
            timestamp_ms: 0,
            user_address: "0x0".to_string(),
            tone_vector: vec![0.5; 32],
            parent_hash: vec![0u8; 32],
        };

        oracle.track_breath(breath.hash.clone());

        let memory_root = oracle.compute_memory_root();
        let delta_hash = blake3::hash(b"test_delta").as_bytes().to_vec();

        let result = oracle.process_evolution_event(
            vec![breath],
            1,
            memory_root,
            delta_hash,
        );

        assert!(result.is_ok());
        let proof = result.unwrap();
        assert_eq!(proof.epoch, 1);
        assert!(oracle.verify_proof(&proof));
    }
}
